source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios,9.0
def default_pods
    pod 'KSSwiftExtension', :path => "../"
    pod 'KSSwiftExtension/RxCocoa', :path => "../"
    pod 'KSSwiftExtension/ViewKit', :path => "../"
    pod 'SwiftLint'
end
target 'IOSExample' do
    default_pods
end

target 'IOSExampleTests' do
    default_pods
end
