source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios,8.0
target 'IOSExample' do
pod 'KSSwiftExtension/RxSwift', :path => "../"
pod 'KSSwiftExtension/RxCocoa', :path => "../"
end
